### ISSUE TITLE
显示逻辑需要修改

### ISSUE THREAD

**Issue by arrebole** [Chef5/stock-bar#10]
旧版本是不在时间段内直接不显示，也许改为不在盘中的时候不去向服务器更新

**Comment by arrebole** [comment]
节假日比较难判断

**Comment by arrebole** [comment]
我目前想不到什么优雅的方案 @Chef5

**Comment by Chef5** [comment]
> 我目前想不到什么优雅的方案 @Chef5

我也觉得不在时间段内直接不显示有些不妥，至于“盘中”还要取决于哪个盘？

现阶段的话，只考虑国内股的话：**可以默认9-16点更新，其余时间不更新；取消时间段配置，改为是否在未开盘时显示配置。**

另外节假日的判断，我觉得只目前需要判断周末即可，每年节假日规划不确定，大可不必我们去判断节假日，后期可以寻找节假日判断的在线接口。

你看这样如何？

**Comment by arrebole** [comment]
我觉得你说的很有道理

**Comment by arrebole** [comment]
![image](https://user-images.githubusercontent.com/35516993/172291495-5c4f3fab-7e63-41de-a370-c417cc155d76.png)

@Chef5

**Comment by Chef5** [comment]
你的意思是暂时不考虑节假日判断，在LoadChooseStocks后直接进行render吧 @arrebole 

后期找到可以判断节假日API后，在LoadChooseStocks后判断一下即可，如果可以，还可以让用户设置是否在节假日显示。

**Comment by arrebole** [comment]
节假日后续考虑吧，那先判断周末 @Chef5

**Comment by Chef5** [comment]
> 节假日后续考虑吧，那先判断周末 @Chef5

可以，那咱们现在加一个配置，让用户决定是否在周末显示吧

**Comment by Chef5** [comment]
render.js
``` js
item.alias ?? item.name,
```

现在渲染优先使用alias，如果alias没有设置就会取股票名称，我觉得应该默认alias为`""`，这样status bar上只会显示股价和涨跌幅的纯数字，这样子才会比较隐蔽些🤓 @arrebole 

可以在new Stock()时就默认给`""` ？

**Comment by arrebole** [comment]
有道理 `alia` 是空字符串应该也会被选择, 只有 null 或者 undefined 时使用 `name` @Chef5
