### ISSUE TITLE
是否有必要使用 `typescript`

### ISSUE THREAD

**Issue by arrebole** [Chef5/stock-bar#18]
考虑是否有必要改用 `typescript` @Chef5

**Comment by Chef5** [comment]
官方建议使用TypeScript： [your-first-extension#next-steps](https://code.visualstudio.com/api/get-started/your-first-extension#next-steps)
> In this guide, we mainly describe how to develop VS Code extension with TypeScript because we believe TypeScript offers the best experience for developing VS Code extensions

我个人也觉得TypeScript更好一些，但我还不太了解用ts开发vscode插件需要注意那些，发布和配置有没有需要更改的

**Comment by Chef5** [comment]
我用ts改了一下，目前没有发现什么问题，分支：[dev-ts](https://github.com/Chef5/stock-bar/tree/dev-ts) @arrebole

**Comment by arrebole** [comment]
> 我用ts改了一下，目前没有发现什么问题，分支：[dev-ts](https://github.com/Chef5/stock-bar/tree/dev-ts) @arrebole

晚上等我瞧一瞧

**Comment by arrebole** [comment]
最近在看量化交易，这边架构再整理一下，可以先搞波动监控提醒

**Comment by arrebole** [comment]
> 我用ts改了一下，目前没有发现什么问题，分支：[dev-ts](https://github.com/Chef5/stock-bar/tree/dev-ts) @arrebole

你的可以F5调试吗？

**Comment by Chef5** [comment]
我这可以直接F5调试的，新增的webpack就是为了编译ts吗？@arrebole
![image](https://user-images.githubusercontent.com/38160059/173470062-1acfdc88-e15d-4c50-accb-58e0c5029710.png)

**Comment by arrebole** [comment]
webpack 主要编译成单文件，官方脚手架有推荐
![image](https://user-images.githubusercontent.com/35516993/173485382-72b28a00-2e2b-49c1-ba45-e40766ae74c1.png)
