### ISSUE TITLE
午盘休息重新开盘后不会自己唤醒更新

### ISSUE THREAD

**Issue by wwdok** [Chef5/stock-bar#23]
作者，你好，有时候股票数据卡着不动了，不知道是什么原因，是不是我一秒调用一次太频繁，数据供应商把我的ip拉入黑名单了
![image](https://user-images.githubusercontent.com/43233772/174531198-454e037d-86ca-4615-9cbe-45cbe535d149.png)
希望上面的显示块显示的是具体的日期，不要今日行情，而是6月20日行情，这样我们也方便知道数据卡在什么时间点上

**Comment by wwdok** [comment]
是我糊涂了，刚刚午休所以没动静。。。第一次使用不好意思

**Comment by Chef5** [comment]
> 或者增加个“刷新”按钮。因为有时候vscode开一个晚上没关，隔天来看，还是昨天的数据，所以这个“刷新”按钮还是挺有用的，希望后面增加一下~

应该是休眠太久，定时器已经失效了。目前可以通过F1，Developer: Reload Window 解决。

添加刷新按钮会显得不够简洁，目前考虑是点击或双击某一个股票进行数据刷新

**Comment by Chef5** [comment]
[v1.0.6](https://github.com/Chef5/stock-bar/releases/tag/v1.0.6) 已修复
