### ISSUE TITLE
增加监控提示系统

### ISSUE THREAD

**Issue by arrebole** [Chef5/stock-bar#26]
![image](https://user-images.githubusercontent.com/35516993/176085799-f0feeb34-bdc1-4b36-acba-260fdd628e91.png)

**Comment by Chef5** [comment]
捕获异常，调用vscode API向用户抛出异常吗？@arrebole

**Comment by arrebole** [comment]
## 监控点
+股价急剧拉升或下降
+买卖单委托急剧减小/增加
