### ISSUE TITLE
baseURL不行了

### ISSUE THREAD

**Issue by yurentle** [Chef5/stock-bar#27]
baseURL不行了，很多代码都获取不了数据了

**Comment by Chef5** [comment]
> baseURL不行了，很多代码都获取不了数据了

插件用的网易的接口，检查了一下，网易接口深市股票暂时无法获取到数据，正在考虑更换数据接口

**Comment by yurentle** [comment]
现在又好了，应该是网易修复了

**Comment by arrebole** [comment]
又不行了，网易的接口有问题，吐出的数不对

**Comment by arrebole** [comment]
@Chef5 不知道是不是网易的接口挂了，还是增加的一些限制

**Comment by arrebole** [comment]
@Chef5 @yurentle #28 看看有没有问题

**Comment by Chef5** [comment]
v1.0.5换成新浪了
