### ISSUE TITLE
新浪的又不行了

### ISSUE THREAD

**Issue by wdwate** [Chef5/stock-bar#29]
这两天stock-bar数据不更新了, 我看了上次的commit是改到了新浪的接口,感觉可能跟新浪有点关系.
是不是跟这个问题类似?看不懂ts, 不知道ts里怎么请求的;
我浏览器直接请求新浪也不行, 但是python里用request加个referer就可以

https://github.com/LeekHub/leek-fund/issues/359

**Comment by Chef5** [comment]
已解决，更新到v1.0.5
