### ISSUE TITLE
默认上证指数数据不正确

### ISSUE THREAD

**Issue by weiyi88** [Chef5/stock-bar#38]
默认的上证指数不正确，还3200多点，这是多少年前的事了

**Comment by Chef5** [comment]
> 默认的上证指数不正确，还3200多点，这是多少年前的事了

我看是3000来点，查了一下其他软件，是对的呢

**Comment by weiyi88** [comment]
![image](https://github.com/Chef5/stock-bar/assets/32037147/cd441758-909b-44d0-839e-6c3092104ac7)
这是我vs code的显示，右边那个才是真正的上证数据，话说，这上证指数数据也应该开发设置，这样会更好

**Comment by Chef5** [comment]
> ![image](https://private-user-images.githubusercontent.com/32037147/308440488-cd441758-909b-44d0-839e-6c3092104ac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNjc4OTMsIm5iZiI6MTcwOTE2NzU5MywicGF0aCI6Ii8zMjAzNzE0Ny8zMDg0NDA0ODgtY2Q0NDE3NTgtOTA5Yi00NGQwLTgzOWUtNmMzMDkyMTA0YWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAwNDYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOTM2OTMyODA0ODU3MjM5NTM5NTY5NzFlZjA2Nzc4ZDk1YThmNDdhNzM0ZjY2NTY2NTRlMzM5ODdhZGQyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CBqVaef4CwCotsZnCGnAmxKeK2QPZhyyRTSr3OKUxQg) 这是我vs code的显示，右边那个才是真正的上证数据，话说，这上证指数数据也应该开发设置，这样会更好

左边这个不是`stock-bar`的数据，因为`stock-bar`没有图标显示，请排查一下你是否安装了其他插件。

**Comment by weiyi88** [comment]
好家伙，还真的是，麻烦了
