### ISSUE TITLE
删除示例里面的期货配置后，底部还是显示铜这个期货示例

### ISSUE THREAD

**Issue by Starsun-sx** [Chef5/stock-bar#45]
如题，如图：![Pasted image 20241017100416](https://github.com/user-attachments/assets/e8a5adb8-7eab-46f0-a23b-00e8e974ee4a)

**Comment by Chef5** [comment]
> 如题，如图：![Pasted image 20241017100416](https://private-user-images.githubusercontent.com/177992377/377284141-e8a5adb8-7eab-46f0-a23b-00e8e974ee4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzQzOTQsIm5iZiI6MTcyOTIzNDA5NCwicGF0aCI6Ii8xNzc5OTIzNzcvMzc3Mjg0MTQxLWU4YTVhZGI4LTdlYWItNDZmMC1hMjNiLTAwZThlOTc0ZWU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwNjQ4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzI2ZmI0MmQwYjY5MDkxNWUzNjY0MDU4NjIwNmNiYTNiYTNjYmM0Njg0OTM5M2UxODE2OTYzZmRmMTNmYjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.STJkxAhPXkZw3B97VDIuLf8Zp_HNzfB7k9-xwg-b0Y0)

没有复现，可以提供一下`"stock-bar.futures"`的完整配置吗
